name: Build and Deploy Docker Image

on:
  workflow_run:
    workflows:
      - Test Application
    types:
      - completed

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@latest
        with:
          username: ${{ secrets.marliyatou }}
          password: ${{ secrets.Lysandre1 }}

      - name: Build Docker image
        run: |
          docker build -t marliyatou/devop_test:latest .

      - name: Push Docker image to Docker Hub
        run: |
          docker push marliyatou/devop_test:latest
